language: python

python:
  - '3.7'
  - '3.8'

before_install:
  - pip install --upgrade pip

install:
  - pip install .

script:
  - python setup.py test

deploy:
  provider: pypi
  user: __token__
  distributions: sdist
  skip_cleanup: true
  password:
    secure: "i6pq6m38O9GIzFHlrJiKszQRge0bfeLF9fIEatbiow4/nMeaFenGTHJbjr7W3qvUzeDZ8Icbd1XYt5SuZxhlCyTdsb7E/W1XqoPHSJUfZwnuBvHxN3wfbO2t2oliiMpBBOt5xqF7GUGhgKOEVVZJj2NCVGjMbmaCjr5Ge+sPCNg098SlK+XL278l9YR1Kaveq9AzRyTzN4k8NuVeRAgGZYuRTEDIpTg9gnlJR4AIRSAYVE3MOP3SJOQWXpe8M2Qhc4slG9wKiCZXc9Crchd5FYbKqCIPLDsihy1aUzi7SZ2B7h1ldPKBkk3+x0IDmrgn7ukZZoHQX1TP4NCrMCqDIXw95m7zMN+By6vJomrka9eoKo0xmpfvHfalBC9ULuOaYin2FQbp4jCEP8feoO05mEVwPF6As4u/LypPQ83uG7JnQ2VD0pvgihUQ0Glfj32ZmInKRL7sqpx9CG59eLNO6CkANEaPMGyFZsyJnvMN0oOx8i1nK3et8UzbFs9uqG5yH/GGFVgyOxFc1niMLBsaaqfHPPc6eVygtMb87FjvG4RXAiLsc7yqUX640vw9WzuGL2RNxmDrSJ+bed/gDthVBr72LjZt5bcQF6EFkJQsaF+CyT2mMwwbezJ3xQ0NU0dIBQkH0EPGBiHrJdiipKOol1IqNF01nUQgUIaf9lmTg34="
  on:
    tags: true
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.7"
