language: python

python:
  - '3.6'

before_install:
  - pip install --upgrade pip

install:
  - pip install .

script:
  - python setup.py test

deploy:
  provider: pypi
  user: fact-deploybot
  password:
    secure: MLAQ1jW1uEI69orE9JKCRp13EamMpSmbv43nv3rFkJnsV5CAIn2vjggQE7xCDlX8gHXdRpe56gYO1PO4z7ldXBRCaw3N2qDNoLM1CDGjc8au5agRftkt4e+x2xK9quykVHXCUc7jybcoJAoe+8nZJEWDDCbCjqA99z1Psxc/aMHeFCwaj4G6fDgmul6pKQDKcpe/axYbjZOcHeiZfZ9XURCRsDwhnp6b6SW0YkOI3p+HPY5vrRXj1cojS8+mz0HT9Jq0tjmzmOwyw1a3YtXQzBdfaTeW+/pPaHLfsxuvZ+vDHr2s/dy0DUZv0N2KZNmsvI7PSGn6b2IBHREELW/CIMd+uKfXWTRd376OhNUCy1z+mywz6ttm9T1Z64YSRAEQ/6exKGWa8AZ3qs0GTfvIhdYvBHDgQ+r/h5nrNW861+vkfGMnS930zJfmr4wD7MuPaHtAjBQGO90/hrJZFZ1sR4CbjVUjCSMQlJ6LplCm9gExU+VYwWj3gh58gTBVDkDsT2oYN3OKUIpvBP06BnTPeCcQwa6vTWkwluHsKlfM1BtdIsBLCXvC8xMpb75T+YLudbDouxGMBYekXxfd5iErTHeVn26Vmj7hFoW7m6qGjHQ4JUTpIjdGf7kLbD1pgEErRVYpd8Ym74/URwHLl4LZlH2SopH16kAFY1CKLs6dA6s=
  on:
    tags: true
    branch: master
