language: python

python:
  - '3.6'

before_install:
  - pip install --upgrade pip

install:
  - pip install .

script:
  - python setup.py test

deploy:
  provider: pypi
  user: fact-deploybot
  password:
    secure: ZhdkRQuv8w91qofNu7Mr8oyvTS3uH1uUFnecemLtNebWa90ykeoOlTmD31fcgUAFLM9DSbu/i0qAItS8/pAzCozRqMwchetD7C254Q2kI/tw7xy/dbOmBcYrTW4WGWeRSALR4wHVPDirScYttugjXCiGYAg52+j1YvcIoVZCL7JSYtXPeIq5bdyLaxnv3YYxcgT61Dp2v5lH3GbszXfDUdKM15d9BuDcya6lx/qzqDstIqInbjaEajRnzvVX1pVNTxX91IkGvB5rl29GlsilhRqMOmbacJpWJH/H6rbeqsns4X+AeM7EO7/rRekake6hvatI2MZFSoDdNgne4JKPZTSNe+u3eRvBkC4OFbnUVOn6Ie5SC28Boyc47m3N4kYQqP1vjofjmhmqUGBjPXnxvH4wIfpOcuGpSH29K3qvTV4enAR70W/eiXn77/sGftFG/PEk7a/sbBN2nAIPKGNkWeDWLDK+s7htQsJ8AQ/uiIfjOy/V18mpHFTxhNpZCHR001M5jT83/zmYcXCWSisMsZAlZ4E8ra/4heuTvNfeuylT5lTcRx3UcjUYTNuHVCibbx89hbAoxx+OSLrzKJkwrN4A++J0E08PDqhMDelKMZBcAAZlzm4MQ5AJQUcezvhku/dgVumbycpVIjXzbkR9AyY5Q15F8KumPXQmB5UdaAM=
  on:
    tags: true
    branch: master
